// Update CURRENT_COHORT when a new cohort opens for registration
export const CURRENT_COHORT = "Cohort 1";

export const ILOILO_BARANGAYS = [
  "Airport (Mandurriao)",
  "Aguinaldo",
  "Atipolo",
  "Avanceña (Molo)",
  "Baluarte (Arevalo)",
  "Balantang",
  "Bantud",
  "Baybay Tanza",
  "Benguit (Lapuz)",
  "Bo. Obrero",
  "Buhang",
  "Buntatala",
  "Burgos (Jaro)",
  "Burgos-Mabini-Plaza",
  "Caingin",
  "Calaparan",
  "Calumpang (Lapuz)",
  "Carpenter Hill",
  "Danao",
  "Demo",
  "Dulonan",
  "Dungon A",
  "Dungon B",
  "Dungon C",
  "Duran (Lapuz)",
  "East Timawa",
  "Fundidor",
  "Gustilo",
  "Hibao-an Norte",
  "Hibao-an Sur",
  "Hinactacan",
  "Hipodromo",
  "Infante (Arevalo)",
  "Ingore",
  "Inday",
  "Intagayan",
  "Javellana",
  "Kasingkasing",
  "Lanit",
  "Lapuz Norte",
  "Lapuz Sur",
  "Libertad (Jaro)",
  "Libertad (La Paz)",
  "Loboc (Lapuz)",
  "Macarthur",
  "Magdalo",
  "Magsaysay",
  "Mali-ao",
  "Malipayon",
  "Mansaya",
  "Mohon (Arevalo)",
  "Nabitasan",
  "Oñate de Leon",
  "Pale Benedicto Rizal",
  "Progreso (Lapuz)",
  "Quintin Salas",
  "Rizal (Jaro)",
  "San Jose (Arevalo)",
  "San Juan (Jaro)",
  "San Nicolas (Jaro)",
  "Santa Maria (Mandurriao)",
  "Sto. Niño Norte",
  "Sto. Niño Sur",
  "Tag-Ibo",
  "Taft Norte",
  "Tagbac",
  "Tanza-Buntatala",
  "Ticud",
  "Ungka I",
  "Ungka II",
  "Other / Hindi ko alam",
];

export const GRADE_LEVELS = [
  "Grade 4",
  "Grade 5",
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Grade 10",
  "Out of school",
];

export const HEARD_FROM_OPTIONS = [
  "Facebook",
  "Flyer / Poster",
  "Friend or Family",
  "Barangay Announcement",
  "Library / Reading Center",
  "SK / Kagawad",
  "Other",
];

export const LOCAL_ROLES = [
  "Manong Driver / Kuya with a Car",
  "Nanay Snack Brigade",
  "Chaperone (Lolo/Lola/Tita/Tito)",
  "Hiligaynon Translator",
  "Flyer Crew / Sari-Sari Connector",
  "Barangay / SK Connector",
  "Facebook Group Admin",
  "Other",
];

export const REMOTE_ROLES = [
  "Accelerator Alumni / Founder",
  "App Builder / Indie Maker",
  "Industry / Big Tech Speaker",
  "UX / Design Specialist",
  "Specialist Engineer",
  "Remote Work Advocate",
  "Hardware Donor (Laptop)",
  "Hardware Donor (Android)",
  "Other",
];
